data: EED
seq: what_is_background
out_dir: ./output
arch: vit_small #["moco_vit_small","moco_vit_base","mae_vit_base","vit_base","resnet50"]
patch_size: 16
min_size: 320
time_surface_decay: 10000
tau: 0.4
gap: 1
fusion_mode: flow #["mean","max","min","img","flow"]
flow_model: RAFT
alpha: 0.4
max_frame: 5

# bs parameters
bilateral_solver:
  use: true
  sigma_spatial: 2
  sigma_luma: 2
  sigma_chroma: 2

# crf parameters
crf: true
single_frame: false

# Dynamic mask refinement parameters
n_last_frames: 10
size_mask_neighborhood: 5
batch_size: 5
topk: 8
radius: 5
chunk_size: 30000.0

# es_to_frames command for command_line_tools
timediff: 00:00:00.005
start_time: 00:00:00.000
finish_time: 00:00:05.000

